// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG6aleA0yaUbz7D2qBK6MQVK2V33KSsUo',
    appId: '1:153243177053:web:15d7de801788ab6a9f7db4',
    messagingSenderId: '153243177053',
    projectId: 'taternak-45ab3',
    authDomain: 'taternak-45ab3.firebaseapp.com',
    storageBucket: 'taternak-45ab3.appspot.com',
    measurementId: 'G-00LM9JLTK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrYEcn6pVHzmKtqC4hsZFkpTXWffb1zK8',
    appId: '1:153243177053:android:3d8fd0744aa52df99f7db4',
    messagingSenderId: '153243177053',
    projectId: 'taternak-45ab3',
    storageBucket: 'taternak-45ab3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPOKojxDGYJRcRkVggUb84qO7q9AZ-9Q0',
    appId: '1:153243177053:ios:0f85de992fd44f6a9f7db4',
    messagingSenderId: '153243177053',
    projectId: 'taternak-45ab3',
    storageBucket: 'taternak-45ab3.appspot.com',
    iosBundleId: 'com.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPOKojxDGYJRcRkVggUb84qO7q9AZ-9Q0',
    appId: '1:153243177053:ios:0156b85fb712f3c79f7db4',
    messagingSenderId: '153243177053',
    projectId: 'taternak-45ab3',
    storageBucket: 'taternak-45ab3.appspot.com',
    iosBundleId: 'com.example.RunnerTests',
  );
}
